### ISSUE TITLE
Проектировщик: пояснительная записка

### ISSUE THREAD

**Issue by JenkaJonka** [JenkaJonka/Schedule-for-student-and-teacher#8]
Подготовить раздел "Проектирование" для пояснительной записки со всеми диаграммами

**Comment by Erodasun** [comment]
Готова часть проектирования по требованиям и диаграммам для пояснительной записки (20.12.2023)
[Часть Проектирование для ПЗ.docx](https://github.com/JenkaJonka/Schedule-for-student-and-teacher/files/13906416/default.docx)
